FROM app-base:latest AS server-builder
USER root
WORKDIR /root/app
COPY server/ ./server/
COPY storage/ ./storage/
RUN ["gradle", "--no-daemon", "--build-cache", ":server:distTar"]
RUN cp ./server/build/distributions/*.tar ./
RUN ["mkdir", "./server-untar"]
RUN tar -xf ./server-*.tar -C ./server-untar --strip-components=1

# Executable
FROM eclipse-temurin:20-jre-jammy
USER root
WORKDIR /root/app
COPY --from=server-builder /root/app/server-untar/ ./
EXPOSE 9090
CMD ["./bin/server", "--storageStoreDirectoryPath", "/root/app/.bitflask"]
