FROM gradle-jdk19:latest
WORKDIR /home/gradle/app
COPY buildSrc/ ./buildSrc/
COPY common/ ./common/
COPY resp/ ./resp/
COPY gradle/ ./gradle/
COPY settings.gradle ./
RUN ["chown", "--recursive", "gradle:gradle", "/home/gradle/"]
